sudo: false

language: php

os:
  - linux

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

env:
  matrix:
    - DRIVER="phpdbg" DEPENDENCIES="high"

  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

matrix:
  include:
    - php: 7.3
    - php: 7.4

install:
  - travis_retry composer install --no-interaction
  - travis_retry composer update --no-interaction

script:
  - phpdbg -qrr vendor/bin/phpunit

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/coverage.clover
